<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-20T22:00:02 IST" name="Suite" finished-at="2024-12-20T22:00:31 IST" duration-ms="29107">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorvalidationsTest.errorValidationTest()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" name="errorValidationTest" class="actualTests.ErrorvalidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" name="submitOrder" class="actualTests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-12-20T22:00:02 IST" name="SubmitOrder Test" finished-at="2024-12-20T22:00:18 IST" duration-ms="15275">
      <class name="actualTests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:02 IST" name="launchApplication" finished-at="2024-12-20T22:00:05 IST" duration-ms="2939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:05 IST" name="submitOrder" data-provider="getData" finished-at="2024-12-20T22:00:10 IST" duration-ms="4250" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Random@me1, email=random1@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:10 IST" name="tearDown" finished-at="2024-12-20T22:00:10 IST" duration-ms="115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:10 IST" name="launchApplication" finished-at="2024-12-20T22:00:11 IST" duration-ms="1723" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:11 IST" name="submitOrder" data-provider="getData" finished-at="2024-12-20T22:00:15 IST" duration-ms="3658" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Random@me0, email=random@email.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:15 IST" name="tearDown" finished-at="2024-12-20T22:00:15 IST" duration-ms="153" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:15 IST" name="launchApplication" finished-at="2024-12-20T22:00:17 IST" duration-ms="1791" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistory()[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:17 IST" name="OrderHistory" finished-at="2024-12-20T22:00:17 IST" depends-on-methods="actualTests.SubmitOrderTest.submitOrder" duration-ms="422" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistory -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:actualTests.SubmitOrderTest@59505b48]" started-at="2024-12-20T22:00:17 IST" name="tearDown" finished-at="2024-12-20T22:00:18 IST" duration-ms="127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- actualTests.SubmitOrderTest -->
    </test> <!-- SubmitOrder Test -->
    <test started-at="2024-12-20T22:00:18 IST" name="ErrorValidation Test" finished-at="2024-12-20T22:00:31 IST" duration-ms="13692">
      <class name="actualTests.ErrorvalidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:18 IST" name="launchApplication" finished-at="2024-12-20T22:00:20 IST" duration-ms="1803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="errorValidationTest()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:20 IST" name="errorValidationTest" finished-at="2024-12-20T22:00:23 IST" duration-ms="3425" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at actualTests.ErrorvalidationsTest.errorValidationTest(ErrorvalidationsTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValidationTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:23 IST" name="tearDown" finished-at="2024-12-20T22:00:23 IST" duration-ms="76" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:23 IST" name="launchApplication" finished-at="2024-12-20T22:00:26 IST" duration-ms="3114" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="errorValidationTest()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:26 IST" name="errorValidationTest" finished-at="2024-12-20T22:00:29 IST" duration-ms="3007" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at actualTests.ErrorvalidationsTest.errorValidationTest(ErrorvalidationsTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorValidationTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:29 IST" name="tearDown" finished-at="2024-12-20T22:00:30 IST" duration-ms="213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:30 IST" name="launchApplication" finished-at="2024-12-20T22:00:31 IST" duration-ms="1768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="fakeTest()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:31 IST" name="fakeTest" finished-at="2024-12-20T22:00:31 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fakeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:actualTests.ErrorvalidationsTest@4be29ed9]" started-at="2024-12-20T22:00:31 IST" name="tearDown" finished-at="2024-12-20T22:00:31 IST" duration-ms="137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- actualTests.ErrorvalidationsTest -->
    </test> <!-- ErrorValidation Test -->
  </suite> <!-- Suite -->
</testng-results>
